uploads = []
outputs = []

[[generated]]
id = "NiuyJRPAio6vsttLafQu1"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "medigo app icon"

[[generated]]
id = "5GwOKB8kXgZDnlPTnh8-L"
uri = "file://artifacts/mobile/assets/images/med_paracetamol.png"
type = "image"
title = "paracetamol pill"

[[generated]]
id = "KYylHqfb6Bl8VNqGYA_kZ"
uri = "file://artifacts/mobile/assets/images/med_capsule.png"
type = "image"
title = "red yellow capsule"

[[generated]]
id = "JOxS-2Qo1T9sw1SpBZfiK"
uri = "file://artifacts/mobile/assets/images/med_syrup.png"
type = "image"
title = "syrup bottle"

[[generated]]
id = "2gxOXLulRUcH-G592-2yB"
uri = "file://artifacts/mobile/assets/images/med_blister.png"
type = "image"
title = "blister pack"

[[generated]]
id = "b0YcS2bE9O7fc__Pju9mv"
uri = "file://artifacts/mobile/assets/images/med_inhaler.png"
type = "image"
title = "inhaler"

[[generated]]
id = "x8yLG_oSMW6c0MznHO6uT"
uri = "file://artifacts/mobile/assets/images/med_vitamin.png"
type = "image"
title = "vitamin tablets"

[[generated]]
id = "l__7vsJ73N1O4rCeUmmj0"
uri = "file://artifacts/mobile/assets/images/med_eyedrops.png"
type = "image"
title = "eye drops bottle"
